# Generated by Django 5.1.1 on 2026-09-28 16:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=120)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('is_anonymous', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('custom', 'Configured Gateway')], default='razorpay', max_length=24)),
                ('provider_order_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('provider_signature', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('created', 'Order Created'), ('pending', 'Payment Pending'), ('completed', 'Verified & Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='don_status_created_idx'), models.Index(fields=['user', '-created_at'], name='don_user_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='donation_positive_amount_constraint')],
            },
        ),
    ]
