# Generated by Django 5.1.1 on 2026-09-28 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('auth_provider', models.CharField(choices=[('email', 'Email & Password'), ('google', 'Google OAuth 2.0')], db_index=True, default='email', max_length=24)),
                ('google_sub_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('email_verified', models.BooleanField(db_index=True, default=False)),
                ('email_verification_token', models.CharField(blank=True, db_index=True, max_length=128)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('security_alerts_enabled', models.BooleanField(default=True)),
                ('last_login_ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['auth_provider', 'email_verified'], name='prof_provider_ver_idx')],
            },
        ),
    ]
