-- InSave Hub Cloudflare D1 Compatible SQL Export
PRAGMA foreign_keys=OFF;
CREATE TABLE "accounts_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "display_name" varchar(120) NOT NULL, "avatar_url" varchar(500) NOT NULL, "auth_provider" varchar(24) NOT NULL, "google_sub_id" varchar(128) NULL UNIQUE, "email_verified" bool NOT NULL, "email_verification_token" varchar(128) NOT NULL, "email_verified_at" datetime NULL, "security_alerts_enabled" bool NOT NULL, "last_login_ip_hash" varchar(64) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "advertisements_adsession" ("id" char(32) NOT NULL PRIMARY KEY, "session_key" varchar(64) NOT NULL, "ip_hash" varchar(64) NOT NULL, "nonce_token" varchar(128) NOT NULL UNIQUE, "required_duration_seconds" integer unsigned NOT NULL CHECK ("required_duration_seconds" >= 0), "started_at" datetime NOT NULL, "eligible_at" datetime NOT NULL, "completed_at" datetime NULL, "status" varchar(16) NOT NULL, "created_at" datetime NOT NULL, "pending_download_id" char(32) NULL REFERENCES "downloads_download" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "advertisements_freeaccesssession" ("id" char(32) NOT NULL PRIMARY KEY, "session_key" varchar(64) NOT NULL, "ip_hash" varchar(64) NOT NULL, "started_at" datetime NOT NULL, "expires_at" datetime NOT NULL, "is_active" bool NOT NULL, "downloads_used_count" integer unsigned NOT NULL CHECK ("downloads_used_count" >= 0), "revoked_reason" varchar(160) NOT NULL, "created_at" datetime NOT NULL, "source_ad_session_id" char(32) NULL UNIQUE REFERENCES "advertisements_adsession" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,2,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,2,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,2,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,2,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,3,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,3,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,3,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,3,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_user','Can add user');
INSERT INTO "auth_permission" VALUES(14,4,'change_user','Can change user');
INSERT INTO "auth_permission" VALUES(15,4,'delete_user','Can delete user');
INSERT INTO "auth_permission" VALUES(16,4,'view_user','Can view user');
INSERT INTO "auth_permission" VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(21,6,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(22,6,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(23,6,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(24,6,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(25,7,'add_siteconfiguration','Can add Site Configuration');
INSERT INTO "auth_permission" VALUES(26,7,'change_siteconfiguration','Can change Site Configuration');
INSERT INTO "auth_permission" VALUES(27,7,'delete_siteconfiguration','Can delete Site Configuration');
INSERT INTO "auth_permission" VALUES(28,7,'view_siteconfiguration','Can view Site Configuration');
INSERT INTO "auth_permission" VALUES(29,8,'add_auditlog','Can add Audit Log');
INSERT INTO "auth_permission" VALUES(30,8,'change_auditlog','Can change Audit Log');
INSERT INTO "auth_permission" VALUES(31,8,'delete_auditlog','Can delete Audit Log');
INSERT INTO "auth_permission" VALUES(32,8,'view_auditlog','Can view Audit Log');
INSERT INTO "auth_permission" VALUES(33,9,'add_profile','Can add User Profile');
INSERT INTO "auth_permission" VALUES(34,9,'change_profile','Can change User Profile');
INSERT INTO "auth_permission" VALUES(35,9,'delete_profile','Can delete User Profile');
INSERT INTO "auth_permission" VALUES(36,9,'view_profile','Can view User Profile');
INSERT INTO "auth_permission" VALUES(37,10,'add_tool','Can add Instagram Tool');
INSERT INTO "auth_permission" VALUES(38,10,'change_tool','Can change Instagram Tool');
INSERT INTO "auth_permission" VALUES(39,10,'delete_tool','Can delete Instagram Tool');
INSERT INTO "auth_permission" VALUES(40,10,'view_tool','Can view Instagram Tool');
INSERT INTO "auth_permission" VALUES(41,11,'add_download','Can add Download');
INSERT INTO "auth_permission" VALUES(42,11,'change_download','Can change Download');
INSERT INTO "auth_permission" VALUES(43,11,'delete_download','Can delete Download');
INSERT INTO "auth_permission" VALUES(44,11,'view_download','Can view Download');
INSERT INTO "auth_permission" VALUES(45,12,'add_downloadattempt','Can add Download Attempt');
INSERT INTO "auth_permission" VALUES(46,12,'change_downloadattempt','Can change Download Attempt');
INSERT INTO "auth_permission" VALUES(47,12,'delete_downloadattempt','Can delete Download Attempt');
INSERT INTO "auth_permission" VALUES(48,12,'view_downloadattempt','Can view Download Attempt');
INSERT INTO "auth_permission" VALUES(49,13,'add_adsession','Can add Advertisement Session');
INSERT INTO "auth_permission" VALUES(50,13,'change_adsession','Can change Advertisement Session');
INSERT INTO "auth_permission" VALUES(51,13,'delete_adsession','Can delete Advertisement Session');
INSERT INTO "auth_permission" VALUES(52,13,'view_adsession','Can view Advertisement Session');
INSERT INTO "auth_permission" VALUES(53,14,'add_freeaccesssession','Can add 24-Hour Free Access Session');
INSERT INTO "auth_permission" VALUES(54,14,'change_freeaccesssession','Can change 24-Hour Free Access Session');
INSERT INTO "auth_permission" VALUES(55,14,'delete_freeaccesssession','Can delete 24-Hour Free Access Session');
INSERT INTO "auth_permission" VALUES(56,14,'view_freeaccesssession','Can view 24-Hour Free Access Session');
INSERT INTO "auth_permission" VALUES(57,15,'add_donation','Can add Donation');
INSERT INTO "auth_permission" VALUES(58,15,'change_donation','Can change Donation');
INSERT INTO "auth_permission" VALUES(59,15,'delete_donation','Can delete Donation');
INSERT INTO "auth_permission" VALUES(60,15,'view_donation','Can view Donation');
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "core_auditlog" ("id" char(32) NOT NULL PRIMARY KEY, "event_type" varchar(64) NOT NULL, "severity" varchar(16) NOT NULL, "actor_ip_hash" varchar(64) NOT NULL, "resource_type" varchar(64) NOT NULL, "resource_id" varchar(128) NOT NULL, "description" text NOT NULL, "metadata" text NOT NULL CHECK ((JSON_VALID("metadata") OR "metadata" IS NULL)), "path" varchar(255) NOT NULL, "method" varchar(16) NOT NULL, "created_at" datetime NOT NULL, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "core_siteconfiguration" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "singleton_id" smallint unsigned NOT NULL UNIQUE CHECK ("singleton_id" >= 0), "site_name" varchar(80) NOT NULL, "tagline" varchar(160) NOT NULL, "maintenance_mode" bool NOT NULL, "ad_countdown_seconds" integer unsigned NOT NULL CHECK ("ad_countdown_seconds" >= 0), "free_access_hours" integer unsigned NOT NULL CHECK ("free_access_hours" >= 0), "free_downloads_before_ad" integer unsigned NOT NULL CHECK ("free_downloads_before_ad" >= 0), "enable_advertisements" bool NOT NULL, "enable_donations" bool NOT NULL, "enable_google_oauth" bool NOT NULL, "enable_guest_downloads" bool NOT NULL, "rate_limit_analyze_per_min" integer unsigned NOT NULL CHECK ("rate_limit_analyze_per_min" >= 0), "rate_limit_download_per_min" integer unsigned NOT NULL CHECK ("rate_limit_download_per_min" >= 0), "rate_limit_auth_per_min" integer unsigned NOT NULL CHECK ("rate_limit_auth_per_min" >= 0), "rate_limit_password_reset_per_hour" integer unsigned NOT NULL CHECK ("rate_limit_password_reset_per_hour" >= 0), "rate_limit_oauth_per_min" integer unsigned NOT NULL CHECK ("rate_limit_oauth_per_min" >= 0), "rate_limit_donation_per_min" integer unsigned NOT NULL CHECK ("rate_limit_donation_per_min" >= 0), "preset_donation_amounts" varchar(120) NOT NULL, "donation_currency" varchar(8) NOT NULL, "minimum_donation_amount" integer unsigned NOT NULL CHECK ("minimum_donation_amount" >= 0), "maximum_donation_amount" integer unsigned NOT NULL CHECK ("maximum_donation_amount" >= 0), "ad_sponsor_title" varchar(120) NOT NULL, "ad_sponsor_body" text NOT NULL, "ad_sponsor_cta_text" varchar(60) NOT NULL, "ad_sponsor_cta_url" varchar(200) NOT NULL, "updated_at" datetime NOT NULL, CONSTRAINT "site_config_singleton_constraint" CHECK ("singleton_id" = 1));
INSERT INTO "core_siteconfiguration" VALUES(1,1,'InSave Hub','Your Instagram Workflow, Refined.',0,30,24,1,1,1,1,1,15,10,8,5,10,6,'100,250,500,1000','INR',50,100000,'Edge Media Delivery Infrastructure','High-throughput content inspection and zero-retention media routing supported by our global network sponsors.','Learn About Our Architecture','https://www.cloudflare.com/','2026-09-28 16:58:59.742919');
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','permission');
INSERT INTO "django_content_type" VALUES(3,'auth','group');
INSERT INTO "django_content_type" VALUES(4,'auth','user');
INSERT INTO "django_content_type" VALUES(5,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(6,'sessions','session');
INSERT INTO "django_content_type" VALUES(7,'core','siteconfiguration');
INSERT INTO "django_content_type" VALUES(8,'core','auditlog');
INSERT INTO "django_content_type" VALUES(9,'accounts','profile');
INSERT INTO "django_content_type" VALUES(10,'downloads','tool');
INSERT INTO "django_content_type" VALUES(11,'downloads','download');
INSERT INTO "django_content_type" VALUES(12,'downloads','downloadattempt');
INSERT INTO "django_content_type" VALUES(13,'advertisements','adsession');
INSERT INTO "django_content_type" VALUES(14,'advertisements','freeaccesssession');
INSERT INTO "django_content_type" VALUES(15,'donations','donation');
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO "django_migrations" VALUES(1,'contenttypes','0001_initial','2026-09-28 16:58:58.130623');
INSERT INTO "django_migrations" VALUES(2,'auth','0001_initial','2026-09-28 16:58:58.151822');
INSERT INTO "django_migrations" VALUES(3,'accounts','0001_initial','2026-09-28 16:58:58.169244');
INSERT INTO "django_migrations" VALUES(4,'admin','0001_initial','2026-09-28 16:58:58.187698');
INSERT INTO "django_migrations" VALUES(5,'admin','0002_logentry_remove_auto_add','2026-09-28 16:58:58.203819');
INSERT INTO "django_migrations" VALUES(6,'admin','0003_logentry_add_action_flag_choices','2026-09-28 16:58:58.212515');
INSERT INTO "django_migrations" VALUES(7,'downloads','0001_initial','2026-09-28 16:58:58.269102');
INSERT INTO "django_migrations" VALUES(8,'advertisements','0001_initial','2026-09-28 16:58:58.368000');
INSERT INTO "django_migrations" VALUES(9,'contenttypes','0002_remove_content_type_name','2026-09-28 16:58:58.395775');
INSERT INTO "django_migrations" VALUES(10,'auth','0002_alter_permission_name_max_length','2026-09-28 16:58:58.413556');
INSERT INTO "django_migrations" VALUES(11,'auth','0003_alter_user_email_max_length','2026-09-28 16:58:58.433465');
INSERT INTO "django_migrations" VALUES(12,'auth','0004_alter_user_username_opts','2026-09-28 16:58:58.445508');
INSERT INTO "django_migrations" VALUES(13,'auth','0005_alter_user_last_login_null','2026-09-28 16:58:58.467586');
INSERT INTO "django_migrations" VALUES(14,'auth','0006_require_contenttypes_0002','2026-09-28 16:58:58.471573');
INSERT INTO "django_migrations" VALUES(15,'auth','0007_alter_validators_add_error_messages','2026-09-28 16:58:58.484292');
INSERT INTO "django_migrations" VALUES(16,'auth','0008_alter_user_username_max_length','2026-09-28 16:58:58.504036');
INSERT INTO "django_migrations" VALUES(17,'auth','0009_alter_user_last_name_max_length','2026-09-28 16:58:58.523991');
INSERT INTO "django_migrations" VALUES(18,'auth','0010_alter_group_name_max_length','2026-09-28 16:58:58.549735');
INSERT INTO "django_migrations" VALUES(19,'auth','0011_update_proxy_permissions','2026-09-28 16:58:58.564336');
INSERT INTO "django_migrations" VALUES(20,'auth','0012_alter_user_first_name_max_length','2026-09-28 16:58:58.611175');
INSERT INTO "django_migrations" VALUES(21,'core','0001_initial','2026-09-28 16:58:58.637702');
INSERT INTO "django_migrations" VALUES(22,'donations','0001_initial','2026-09-28 16:58:58.660756');
INSERT INTO "django_migrations" VALUES(23,'sessions','0001_initial','2026-09-28 16:58:58.672531');
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "donations_donation" ("id" char(32) NOT NULL PRIMARY KEY, "donor_name" varchar(120) NOT NULL, "donor_email" varchar(254) NOT NULL, "is_anonymous" bool NOT NULL, "amount" decimal NOT NULL, "currency" varchar(8) NOT NULL, "message" varchar(280) NOT NULL, "provider" varchar(24) NOT NULL, "provider_order_id" varchar(128) NOT NULL UNIQUE, "provider_payment_id" varchar(128) NOT NULL, "provider_signature" varchar(256) NOT NULL, "status" varchar(20) NOT NULL, "ip_hash" varchar(64) NOT NULL, "completed_at" datetime NULL, "created_at" datetime NOT NULL, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "donation_positive_amount_constraint" CHECK ("amount" > '0'));
CREATE TABLE "downloads_download" ("id" char(32) NOT NULL PRIMARY KEY, "session_key" varchar(64) NOT NULL, "ip_hash" varchar(64) NOT NULL, "source_url" varchar(500) NOT NULL, "shortcode" varchar(64) NOT NULL, "content_type" varchar(24) NOT NULL, "media_format" varchar(80) NOT NULL, "resolution" varchar(40) NOT NULL, "file_size_bytes" bigint NOT NULL, "file_size_label" varchar(32) NOT NULL, "media_title" varchar(240) NOT NULL, "author_handle" varchar(80) NOT NULL, "preview_metadata" text NOT NULL CHECK ((JSON_VALID("preview_metadata") OR "preview_metadata" IS NULL)), "download_token" varchar(128) NOT NULL UNIQUE, "status" varchar(24) NOT NULL, "access_mode" varchar(24) NOT NULL, "completed_at" datetime NULL, "created_at" datetime NOT NULL, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "tool_id" bigint NULL REFERENCES "downloads_tool" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "downloads_downloadattempt" ("id" char(32) NOT NULL PRIMARY KEY, "raw_url" varchar(500) NOT NULL, "normalized_url" varchar(500) NOT NULL, "ip_hash" varchar(64) NOT NULL, "status" varchar(32) NOT NULL, "reason" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "download_id" char(32) NULL REFERENCES "downloads_download" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "tool_id" bigint NULL REFERENCES "downloads_tool" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "downloads_tool" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(120) NOT NULL UNIQUE, "slug" varchar(120) NOT NULL UNIQUE, "category" varchar(24) NOT NULL, "short_description" varchar(220) NOT NULL, "detailed_description" text NOT NULL, "supported_url_hint" varchar(160) NOT NULL, "output_formats" varchar(120) NOT NULL, "badge_code" varchar(16) NOT NULL, "is_active" bool NOT NULL, "is_featured" bool NOT NULL, "display_order" smallint unsigned NOT NULL CHECK ("display_order" >= 0), "total_uses" integer unsigned NOT NULL CHECK ("total_uses" >= 0), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO "downloads_tool" VALUES(1,'Instagram Reel Downloader','reel-downloader','reel','Extract public vertical Reels in original frame rate with synchronized audio tracks.','Designed for creators and social media archivists managing public short-form video. Inspects public Reel streams, verifies codec parameters, and packages MP4 containers without watermarks or re-compression artifacts.','https://www.instagram.com/reel/C8xYz123AbC/','MP4 (H.264 1080x1920) / AAC Stereo','MOD-01',1,1,1,0,'2026-09-28 16:58:59.750308','2026-09-28 16:58:59.750308');
INSERT INTO "downloads_tool" VALUES(2,'Instagram Video Downloader','video-downloader','video','Download long-form public video broadcasts and feed videos at native bitrate.','Supports public feed videos and archival IGTV links. Resolves highest available public progressive or segmented video streams with full frame-dimension telemetry.','https://www.instagram.com/tv/C7vBn987XyZ/','MP4 (1080p / 720p) / AAC','MOD-02',1,1,2,0,'2026-09-28 16:58:59.756335','2026-09-28 16:58:59.756335');
INSERT INTO "downloads_tool" VALUES(3,'Instagram Image Downloader','image-downloader','image','Retrieve full-resolution public photography assets with original color profile.','Inspects public single-image posts and extracts the highest-resolution public CDN rendition (up to 1080x1350 portrait or 1080x1080 square) in clean sRGB format.','https://www.instagram.com/p/C9pQr456LmN/','JPEG / SVG High-Precision Preview','MOD-03',1,1,3,0,'2026-09-28 16:58:59.762570','2026-09-28 16:58:59.762570');
INSERT INTO "downloads_tool" VALUES(4,'Public Post Downloader','public-post-downloader','post','Unified inspector for multi-slide carousels and mixed-media public publications.','Automatically detects whether a public /p/ permalink contains a single photograph, a video clip, or a multi-item carousel package, presenting structured format options.','https://www.instagram.com/p/C6kLm321OpQ/','MP4 / JPEG / Structured Manifest','MOD-04',1,1,4,0,'2026-09-28 16:58:59.768574','2026-09-28 16:58:59.768574');
INSERT INTO "downloads_tool" VALUES(5,'Profile Media Utility','profile-media-utility','profile','Inspect public profile identity headers, avatar dimensions, and public handle status.','Provides a clean verification summary for public creator and brand handles, including public avatar asset resolution and canonical permalink structure.','https://www.instagram.com/instagram/','Profile Avatar Package / JSON Summary','MOD-05',1,1,5,0,'2026-09-28 16:58:59.773985','2026-09-28 16:58:59.773985');
INSERT INTO "downloads_tool" VALUES(6,'Content Information Extractor','content-info-extractor','metadata','Generate structured technical metadata reports for public Instagram permalinks.','Extracts public shortcode identifiers, canonical URLs, aspect ratio geometry, and publication parameters into a clean JSON document for editorial workflows.','https://www.instagram.com/p/C5aBc789DeF/','JSON Technical Manifest','MOD-06',1,1,6,0,'2026-09-28 16:58:59.779982','2026-09-28 16:58:59.779982');
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "accounts_profile_auth_provider_bd5834a5" ON "accounts_profile" ("auth_provider");
CREATE INDEX "accounts_profile_email_verified_cb771fc1" ON "accounts_profile" ("email_verified");
CREATE INDEX "accounts_profile_email_verification_token_8af9e425" ON "accounts_profile" ("email_verification_token");
CREATE INDEX "accounts_profile_created_at_121a5afc" ON "accounts_profile" ("created_at");
CREATE INDEX "prof_provider_ver_idx" ON "accounts_profile" ("auth_provider", "email_verified");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "dl_user_status_idx" ON "downloads_download" ("user_id", "status", "created_at" DESC);
CREATE INDEX "dl_sess_status_idx" ON "downloads_download" ("session_key", "status", "created_at" DESC);
CREATE INDEX "dl_shortcode_idx" ON "downloads_download" ("shortcode", "created_at" DESC);
CREATE INDEX "downloads_tool_category_c21ead0f" ON "downloads_tool" ("category");
CREATE INDEX "downloads_tool_is_active_a3f816d6" ON "downloads_tool" ("is_active");
CREATE INDEX "tool_active_ord_idx" ON "downloads_tool" ("is_active", "display_order");
CREATE INDEX "downloads_download_session_key_cca6b04f" ON "downloads_download" ("session_key");
CREATE INDEX "downloads_download_ip_hash_2f06a92f" ON "downloads_download" ("ip_hash");
CREATE INDEX "downloads_download_shortcode_60d13b23" ON "downloads_download" ("shortcode");
CREATE INDEX "downloads_download_content_type_3d3cff83" ON "downloads_download" ("content_type");
CREATE INDEX "downloads_download_status_33c451c2" ON "downloads_download" ("status");
CREATE INDEX "downloads_download_completed_at_c22e0d38" ON "downloads_download" ("completed_at");
CREATE INDEX "downloads_download_created_at_2fb24127" ON "downloads_download" ("created_at");
CREATE INDEX "downloads_download_user_id_3e9b9d72" ON "downloads_download" ("user_id");
CREATE INDEX "downloads_download_tool_id_6f0fabd8" ON "downloads_download" ("tool_id");
CREATE INDEX "downloads_downloadattempt_ip_hash_5acc5e18" ON "downloads_downloadattempt" ("ip_hash");
CREATE INDEX "downloads_downloadattempt_status_769a87eb" ON "downloads_downloadattempt" ("status");
CREATE INDEX "downloads_downloadattempt_created_at_61c7742c" ON "downloads_downloadattempt" ("created_at");
CREATE INDEX "downloads_downloadattempt_download_id_e9cd2820" ON "downloads_downloadattempt" ("download_id");
CREATE INDEX "downloads_downloadattempt_user_id_02b7d5e7" ON "downloads_downloadattempt" ("user_id");
CREATE INDEX "downloads_downloadattempt_tool_id_d3114fe4" ON "downloads_downloadattempt" ("tool_id");
CREATE INDEX "dl_att_status_idx" ON "downloads_downloadattempt" ("status", "created_at" DESC);
CREATE INDEX "dl_att_ip_idx" ON "downloads_downloadattempt" ("ip_hash", "created_at" DESC);
CREATE INDEX "ad_user_status_idx" ON "advertisements_adsession" ("user_id", "status", "started_at" DESC);
CREATE INDEX "ad_sess_status_idx" ON "advertisements_adsession" ("session_key", "status", "started_at" DESC);
CREATE INDEX "free_user_active_exp_idx" ON "advertisements_freeaccesssession" ("user_id", "is_active", "expires_at");
CREATE INDEX "free_sess_active_exp_idx" ON "advertisements_freeaccesssession" ("session_key", "is_active", "expires_at");
CREATE INDEX "advertisements_adsession_session_key_d9c266ec" ON "advertisements_adsession" ("session_key");
CREATE INDEX "advertisements_adsession_ip_hash_f16caba9" ON "advertisements_adsession" ("ip_hash");
CREATE INDEX "advertisements_adsession_started_at_3583bf80" ON "advertisements_adsession" ("started_at");
CREATE INDEX "advertisements_adsession_eligible_at_23476073" ON "advertisements_adsession" ("eligible_at");
CREATE INDEX "advertisements_adsession_status_d8d4141d" ON "advertisements_adsession" ("status");
CREATE INDEX "advertisements_adsession_pending_download_id_2a697d50" ON "advertisements_adsession" ("pending_download_id");
CREATE INDEX "advertisements_adsession_user_id_3382313e" ON "advertisements_adsession" ("user_id");
CREATE INDEX "advertisements_freeaccesssession_session_key_845eba48" ON "advertisements_freeaccesssession" ("session_key");
CREATE INDEX "advertisements_freeaccesssession_ip_hash_171f17d5" ON "advertisements_freeaccesssession" ("ip_hash");
CREATE INDEX "advertisements_freeaccesssession_started_at_696a8e06" ON "advertisements_freeaccesssession" ("started_at");
CREATE INDEX "advertisements_freeaccesssession_expires_at_fc773f1e" ON "advertisements_freeaccesssession" ("expires_at");
CREATE INDEX "advertisements_freeaccesssession_is_active_944842fe" ON "advertisements_freeaccesssession" ("is_active");
CREATE INDEX "advertisements_freeaccesssession_user_id_d8ad9244" ON "advertisements_freeaccesssession" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "core_auditlog_event_type_17aaf6e2" ON "core_auditlog" ("event_type");
CREATE INDEX "core_auditlog_severity_9d26bf93" ON "core_auditlog" ("severity");
CREATE INDEX "core_auditlog_actor_ip_hash_29f1071d" ON "core_auditlog" ("actor_ip_hash");
CREATE INDEX "core_auditlog_created_at_3d40b819" ON "core_auditlog" ("created_at");
CREATE INDEX "core_auditlog_user_id_3797aaab" ON "core_auditlog" ("user_id");
CREATE INDEX "audit_evt_created_idx" ON "core_auditlog" ("event_type", "created_at" DESC);
CREATE INDEX "audit_sev_created_idx" ON "core_auditlog" ("severity", "created_at" DESC);
CREATE INDEX "donations_donation_is_anonymous_17d625dd" ON "donations_donation" ("is_anonymous");
CREATE INDEX "donations_donation_provider_payment_id_1fdf083a" ON "donations_donation" ("provider_payment_id");
CREATE INDEX "donations_donation_status_6c73bb41" ON "donations_donation" ("status");
CREATE INDEX "donations_donation_ip_hash_c6d645a6" ON "donations_donation" ("ip_hash");
CREATE INDEX "donations_donation_created_at_961638a1" ON "donations_donation" ("created_at");
CREATE INDEX "donations_donation_user_id_04dd09bd" ON "donations_donation" ("user_id");
CREATE INDEX "don_status_created_idx" ON "donations_donation" ("status", "created_at" DESC);
CREATE INDEX "don_user_created_idx" ON "donations_donation" ("user_id", "created_at" DESC);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
