# Generated by Django 5.1.1 on 2026-09-28 16:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('site_name', models.CharField(default='InSave Hub', max_length=80)),
                ('tagline', models.CharField(default='Your Instagram Workflow, Refined.', max_length=160)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('ad_countdown_seconds', models.PositiveIntegerField(default=30, help_text='Server-enforced countdown duration in seconds before unlocking next download.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('free_access_hours', models.PositiveIntegerField(default=24, help_text='Duration in hours of uninterrupted access granted after completing an ad session.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('free_downloads_before_ad', models.PositiveIntegerField(default=1, help_text='Number of completed downloads permitted before triggering the 30-second ad gate.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('enable_advertisements', models.BooleanField(default=True)),
                ('enable_donations', models.BooleanField(default=True)),
                ('enable_google_oauth', models.BooleanField(default=True)),
                ('enable_guest_downloads', models.BooleanField(default=True)),
                ('rate_limit_analyze_per_min', models.PositiveIntegerField(default=15)),
                ('rate_limit_download_per_min', models.PositiveIntegerField(default=10)),
                ('rate_limit_auth_per_min', models.PositiveIntegerField(default=8)),
                ('rate_limit_password_reset_per_hour', models.PositiveIntegerField(default=5)),
                ('rate_limit_oauth_per_min', models.PositiveIntegerField(default=10)),
                ('rate_limit_donation_per_min', models.PositiveIntegerField(default=6)),
                ('preset_donation_amounts', models.CharField(default='100,250,500,1000', help_text='Comma-separated preset donation amounts in the configured currency.', max_length=120)),
                ('donation_currency', models.CharField(default='INR', max_length=8)),
                ('minimum_donation_amount', models.PositiveIntegerField(default=50)),
                ('maximum_donation_amount', models.PositiveIntegerField(default=100000)),
                ('ad_sponsor_title', models.CharField(default='Edge Media Delivery Infrastructure', max_length=120)),
                ('ad_sponsor_body', models.TextField(default='High-throughput content inspection and zero-retention media routing supported by our global network sponsors.')),
                ('ad_sponsor_cta_text', models.CharField(default='Learn About Our Architecture', max_length=60)),
                ('ad_sponsor_cta_url', models.URLField(default='https://www.cloudflare.com/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_id', 1)), name='site_config_singleton_constraint')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('actor_ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='audit_evt_created_idx'), models.Index(fields=['severity', '-created_at'], name='audit_sev_created_idx')],
            },
        ),
    ]
