# Generated by Django 5.1.1 on 2026-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='adsense_publisher_id',
            field=models.CharField(blank=True, default='', help_text='Google AdSense Publisher ID (e.g. pub-1234567890123456 or ca-pub-1234567890123456). Falls back to ADSENSE_PUBLISHER_ID environment variable if blank.', max_length=64),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_adsense',
            field=models.BooleanField(default=True, help_text='Master toggle to enable or disable Google AdSense scripts and ad slots site-wide.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_adsense_auto_ads',
            field=models.BooleanField(default=True, help_text='Enable Google Auto Ads tag in the head section.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_search_console_verification',
            field=models.CharField(blank=True, default='', help_text='Google Search Console verification code (content attribute of google-site-verification meta tag).', max_length=128),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='INSTASAVE HUB', max_length=80),
        ),
    ]
