# Generated by Django 5.1.1 on 2026-10-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_adsense_publisher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_app_icon',
            field=models.CharField(default='/static/images/icon-512.png', help_text='Primary app icon path or URL (defaults to /static/images/icon-512.png).', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_background_color',
            field=models.CharField(default='#030712', help_text='Hex color code for splash screen background (e.g. #030712).', max_length=16),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_description',
            field=models.TextField(default='Download public Instagram Videos, Reels, Photos, and Carousels in 1080p MP4 and JPEG.', help_text='Application description provided to PWA installers.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_install_button_text',
            field=models.CharField(default='Install App', help_text='Label on the install button (e.g. Install App or Download App).', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_name',
            field=models.CharField(default='INSTASAVE HUB — Instagram Video & Post Downloader', help_text='Full application name displayed on device install screens.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_short_name',
            field=models.CharField(default='INSTASAVE HUB', help_text='Short application name displayed on device home screens.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_start_url',
            field=models.CharField(default='/?source=pwa', help_text='Entry URL launched when opening the installed PWA.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pwa_theme_color',
            field=models.CharField(default='#030712', help_text='Hex color code for mobile status bar and browser frame (e.g. #030712).', max_length=16),
        ),
    ]
