# Generated by Django 5.1.1 on 2026-09-28 16:58

import apps.downloads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('reel', 'Reel Utility'), ('video', 'Video Utility'), ('image', 'Image Utility'), ('post', 'Public Post Utility'), ('profile', 'Profile Media Utility'), ('metadata', 'Content Information Extractor')], db_index=True, default='reel', max_length=24)),
                ('short_description', models.CharField(max_length=220)),
                ('detailed_description', models.TextField()),
                ('supported_url_hint', models.CharField(default='https://www.instagram.com/reel/C8xYz123AbC/', max_length=160)),
                ('output_formats', models.CharField(default='MP4 (H.264) / Original Audio', max_length=120)),
                ('badge_code', models.CharField(default='MOD-01', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Tool',
                'verbose_name_plural': 'Instagram Tools',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='tool_active_ord_idx')],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_url', models.URLField(max_length=500)),
                ('shortcode', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.CharField(choices=[('reel', 'Instagram Reel'), ('video', 'Instagram Video'), ('image', 'Instagram Photograph'), ('post', 'Public Post / Carousel'), ('profile', 'Public Profile Media'), ('metadata', 'Content Information Package')], db_index=True, default='reel', max_length=24)),
                ('media_format', models.CharField(default='MP4 1080p', max_length=80)),
                ('resolution', models.CharField(default='1080x1920', max_length=40)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_size_label', models.CharField(default='8.4 MB', max_length=32)),
                ('media_title', models.CharField(max_length=240)),
                ('author_handle', models.CharField(blank=True, max_length=80)),
                ('preview_metadata', models.JSONField(blank=True, default=dict)),
                ('download_token', models.CharField(db_index=True, default=apps.downloads.models.generate_download_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Analyzed & Ready'), ('ad_locked', 'Awaiting 30s Advertisement'), ('completed', 'Download Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='ready', max_length=24)),
                ('access_mode', models.CharField(choices=[('initial_free', 'Initial Free Allowance'), ('ad_unlocked', '30s Ad Unlocked'), ('free_24h_pass', '24-Hour Free Access Pass')], default='initial_free', max_length=24)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='downloads.tool')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_url', models.CharField(max_length=500)),
                ('normalized_url', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('blocked_ad_required', 'Blocked (30s Ad Required)'), ('blocked_rate_limit', 'Blocked (Rate Limited)'), ('invalid_url', 'Rejected (Invalid URL)'), ('restricted_content', 'Rejected (Private/Restricted)'), ('completed', 'Download Completed')], db_index=True, max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('download', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='downloads.download')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_attempts', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='downloads.tool')),
            ],
            options={
                'verbose_name': 'Download Attempt',
                'verbose_name_plural': 'Download Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dl_att_status_idx'), models.Index(fields=['ip_hash', '-created_at'], name='dl_att_ip_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['user', 'status', '-created_at'], name='dl_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['session_key', 'status', '-created_at'], name='dl_sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['shortcode', '-created_at'], name='dl_shortcode_idx'),
        ),
    ]
