# Generated by Django 5.1.1 on 2026-09-28 16:58

import apps.advertisements.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('nonce_token', models.CharField(db_index=True, default=apps.advertisements.models.generate_ad_nonce, max_length=128, unique=True)),
                ('required_duration_seconds', models.PositiveIntegerField(default=30)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('eligible_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active Countdown'), ('completed', 'Completed'), ('expired', 'Expired'), ('invalidated', 'Invalidated')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_download', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_sessions', to='downloads.download')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement Session',
                'verbose_name_plural': 'Advertisement Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('downloads_used_count', models.PositiveIntegerField(default=0)),
                ('revoked_reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ad_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_free_session', to='advertisements.adsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_access_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '24-Hour Free Access Session',
                'verbose_name_plural': '24-Hour Free Access Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adsession',
            index=models.Index(fields=['user', 'status', '-started_at'], name='ad_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='adsession',
            index=models.Index(fields=['session_key', 'status', '-started_at'], name='ad_sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='freeaccesssession',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='free_user_active_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='freeaccesssession',
            index=models.Index(fields=['session_key', 'is_active', 'expires_at'], name='free_sess_active_exp_idx'),
        ),
    ]
