# Generated by Django 5.1.1 on 2026-09-29 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adsession',
            name='ad_type',
            field=models.CharField(choices=[('initial_5s', '5-Second Initial Download Ad'), ('unlock_30s', '30-Second 24-Hour Unlock Ad')], db_index=True, default='unlock_30s', max_length=16),
        ),
        migrations.CreateModel(
            name='DownloadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('first_download_completed', models.BooleanField(db_index=True, default=False)),
                ('ad_completed', models.BooleanField(db_index=True, default=False)),
                ('ad_completed_at', models.DateTimeField(blank=True, null=True)),
                ('access_started_at', models.DateTimeField(blank=True, null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Session',
                'verbose_name_plural': 'Download Sessions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'access_expires_at'], name='dlsess_user_exp_idx'), models.Index(fields=['session_key', 'access_expires_at'], name='dlsess_key_exp_idx')],
            },
        ),
    ]
